### ISSUE TITLE
Fix forms markup

### ISSUE THREAD

**Issue by ivan-kleshnin** [Paqmind/react-starter#14]
Buttons are under avatar. Should be under fields.

**Comment by scabbiaza** [comment]
https://github.com/Paqmind/react-starter/pull/17

**Comment by scabbiaza** [comment]
Btw, I updated Loading component styles and have q about this component.
Why we use it only on robot pages? and not on home/about pages?

**Comment by ivan-kleshnin** [comment]
> Why we use it only on robot pages? and not on home/about pages?
There is no dynamic content

> Pls check this pull-request 
+

**Comment by scabbiaza** [comment]
Should be fixed after merging https://github.com/Paqmind/react-starter/pull/17
