### ISSUE TITLE
Title is misplaced without avatar

### ISSUE THREAD

**Issue by ivan-kleshnin** [Paqmind/react-starter#19]
https://docs.google.com/file/d/0B9bW0B92XgnANjRNQkVkNUtjdHM/edit?usp=drivesdk
I think it's our fault (irregarding of https://github.com/Paqmind/react-starter/issues/14)

**Comment by scabbiaza** [comment]
Don't have permissions to see file on google drive

**Comment by ivan-kleshnin** [comment]
Sorry, made public

**Comment by scabbiaza** [comment]
Should be fixed after merging Pull request  https://github.com/Paqmind/react-starter/pull/17
