### ISSUE TITLE
Check react-headroom component

### ISSUE THREAD

**Issue by ivan-kleshnin** [Paqmind/react-starter#21]
http://kyleamathews.github.io/react-headroom/

**Comment by scabbiaza** [comment]
Here is my opinion:

1. It's interesting to see such component. We have it now as script, may be we need to create a component too.

2. I don't understand what language they use and how to compile it.
Look at the extensions: `.cjsx`, `cofee`:
https://github.com/KyleAMathews/react-headroom/tree/master/src

3. I added extra code to deal with the menu on mobile in header. They don't have it.

4. They propose to add styles in the component's initialization:
```
<Headroom style={{
  webkitTransition: "all .5s ease-in-out"
  mozTransition: "all .5s ease-in-out"
  oTransition: "all .5s ease-in-out"
  transition: "all .5s ease-in-out"
}}>
```

I think it's too much. Yes, they say it's optional and we can use css, but still.

Summary: I don't see advantage of using this component, but it's good example how to create component from our plain script.

**Comment by ivan-kleshnin** [comment]
> I don't understand what language they use and how to compile it.
Look at the extensions: .cjsx, cofee:
https://github.com/KyleAMathews/react-headroom/tree/master/src

Thats coffeescript :(

> Summary: I don't see advantage of using this component, but it's good example how to create component from our plain script.

We use jQuery just to implement this navbar. If it's on React – no more jQuery. That's advantage.

**Comment by scabbiaza** [comment]
Will do

**Comment by scabbiaza** [comment]
`bootstrap.js` requires `jquery` and we use first one for collapsing header menu.
And we can use bootstrap more in the future.

Working with plan js requires add extra code for browser supports. Compare:
```js
let topPosition = window.pageYOffset || document.documentElement.scrollTop;
```

instead of
```js
let topPosition = $(window).scrollTop();
```

or
```js
let body = document.body, html = document.documentElement;
    let documentHeight = Math.max(body.scrollHeight, body.offsetHeight,
                                   html.clientHeight, html.scrollHeight, html.offsetHeight);
```
instead of 
```js
let documentHeight = $(document).height();
```

**Comment by ivan-kleshnin** [comment]
I forgot about bootstrap dependency, hacking everything bottom-up, sorry.
You can use jQuery then.

**Comment by scabbiaza** [comment]
Pls check this pull request https://github.com/Paqmind/react-starter/pull/26
