### ISSUE TITLE
Consider Reflux replacement

### ISSUE THREAD

**Issue by ivan-kleshnin** [Paqmind/react-starter#28]
I'm getting tired of Reflux. They seems to be really lost in what they do. Actions are flawed.

Candidates to watch and replace:
[**Flummox**](https://github.com/acdlite/flummox)
[**Minimal Flux**](https://github.com/malte-wessel/minimal-flux)
[**Rx-Flux**](https://github.com/fdecampredon/rx-flux)
[**ThunderCats**](https://github.com/r3dm/thundercats) (remix of the prev one)

Both are better then Reflux. I like API of the second one more, but it doesn't support async actions at this moment. It's better to wait a bit and see what will happen next.

**Comment by ivan-kleshnin** [comment]
Another option is to completely ditch React and move to CycleJS 
Benefits: CycleJS > ReactJS (it's much more intelligent library)
Drawbacks: lack of docs, examples and my own understanding of Rx concepts.

**Comment by ivan-kleshnin** [comment]
Relevant links:

https://github.com/acdlite/flummox/issues/63

**Comment by ivan-kleshnin** [comment]
Another interesting one is [Baobab](http://christianalfoni.github.io/javascript/2015/02/06/plant-a-baobab-tree-in-your-flux-application.html). Quote:

> Baobab is a JavaScript data tree supporting cursors and enabling developers to easily navigate and monitor nested data. It is mainly inspired by functional zippers such as Clojure's ones and by Om's cursors. It can be paired with React easily through mixins to provide a centralized model holding your application's state.

**Comment by ivan-kleshnin** [comment]
Transition to Baobab in progress.

Please help to deal with forms:
https://github.com/Yomguithereal/baobab/issues/145

**Comment by ivan-kleshnin** [comment]
Beta version of Baobab branch is released. 
State questions are solved to some degree. Please read source.

**Comment by scabbiaza** [comment]
Thank you for sharing this! Looks very, very good!

This action looks very nice:
https://github.com/Paqmind/react-starter/blob/baobab/frontend/app/robot/actions/add.js

And it's a pain, isn't?
https://github.com/Paqmind/react-starter/blob/baobab/frontend/app/robot/components/add.js

I have some questions:

1. https://github.com/Paqmind/react-starter/blob/baobab/frontend/app/robot/models.js#L5
Don't understand why to call here `Alert`? in `robot/models`?

2. Don't understand, who will catch that:
https://github.com/Paqmind/react-starter/blob/baobab/frontend/app/robot/actions/loadmany.js#L22

3. https://github.com/Paqmind/react-starter/blob/baobab/frontend/app/robot/actions/loadmany.js#L26
`loadError` will be `undefined` here, no?
so this will not work:
https://github.com/Paqmind/react-starter/blob/baobab/frontend/app/robot/components/index.js#L25

4. What is the case for `loadOne`? When it can be called?

5. In case of failed removing on backend:
https://github.com/Paqmind/react-starter/blob/baobab/frontend/app/robot/actions/remove.js#L25
So we will see alert + if we are on list page item will be added to this list, right? nice!
Can we add link on detail page on this alert for better usability:
`addAlert({message: "Action `Robot.remove` failed", category: "error"});`

**Comment by ivan-kleshnin** [comment]
> And it's a pain, isn't?
No. Just all complexity is exposed there now and can easily be refactored later. 
I just don't want to hurry with this.

> 2. Don't understand, who will catch that:
Environment. Browser or Node.js. We need to rethrow all errors besides HTTP. Otherwise they will be swallowed and fail silently.

**Comment by ivan-kleshnin** [comment]
> _5. In case of failed removing on backend... So we will see alert + if we are on list page item will be added to this list, right? nice!

I don't get how removal can cause item addition. Typo?

**Comment by scabbiaza** [comment]
Thank you!

*About removing*
In this row old model will be added to the list of models, right?
https://github.com/Paqmind/react-starter/blob/baobab/frontend/app/robot/actions/remove.js#L32

Component, that use this data, will be updated.
So in case if user is on list page, he/she will see that this deleted element will appear on the page.

Is it correct?

**Comment by ivan-kleshnin** [comment]
> In this row old model will be added to the list of models, right?
https://github.com/Paqmind/react-starter/blob/baobab/frontend/app/robot/actions/remove.js#L32
Component, that use this data, will be updated.
So in case if user is on list page, he/she will see that this deleted element will appear on the page.
Is it correct?

Yes
