### ISSUE TITLE
Loading / error icons

### ISSUE THREAD

**Issue by scabbiaza** [Paqmind/react-starter#31]
Alternatives to current loading icon:
http://fortawesome.github.io/Font-Awesome/icon/spinner/
http://fortawesome.github.io/Font-Awesome/icon/refresh/

Error icons:
http://fortawesome.github.io/Font-Awesome/icon/exclamation-triangle/
http://fortawesome.github.io/Font-Awesome/icon/times-circle-o/

**Comment by ivan-kleshnin** [comment]
I don't think they are 100% suitable. What about icon combination?
Cog + http://fortawesome.github.io/Font-Awesome/icon/ban/

**Comment by scabbiaza** [comment]
I like it!

**Comment by scabbiaza** [comment]
https://github.com/Paqmind/react-starter/pull/37

**Comment by ivan-kleshnin** [comment]
Done. Great job!
