### ISSUE TITLE
Init value for model in detail/edit views

### ISSUE THREAD

**Issue by scabbiaza** [Paqmind/react-starter#36]
Try to call not exist robot, in `detail` view you will see `model: undefined`
in `edit` – `model: Object{}`

Can we have one format?

**Comment by ivan-kleshnin** [comment]
Not so easy. Object comes from here:
```javascript
getInitialState() {
  return {
    model: Object.assign({}, this.props.loadModel), // <---------
  }
}
```

Can be:
```javascript
getInitialState() {
  return {
    model: this.props.loadModel ? Object.assign({}, this.props.loadModel) : undefined,
  }
}
```

**Comment by scabbiaza** [comment]
Looks like this condition should be not only there, but here also:
```
componentWillReceiveProps(props) {
    if (isEmpty(this.state.model)) {
      this.setState({
        model: Object.assign({}, props.loadModel),
      })
    }
  },
```

I used `isEmpty()` to check is it undefined or empty model (see comment in pull-request https://github.com/Paqmind/react-starter/pull/37).

May be it ok

**Comment by ivan-kleshnin** [comment]
Yes, that's why I kept both `undefined` and `{}` version: they are hard to remove.
