### ISSUE TITLE
What is vendors.js?

### ISSUE THREAD

**Issue by scabbiaza** [Paqmind/react-starter#38]
I thought it will contain outer libs like `bootstrap` and `jquery`.
But it doesn't.

It contains this:
```js
"frontendVendors": [
    "axios",
    "babel/polyfill",
    "baobab",
    "classnames",
    "node-uuid",
    "util-inspect",
    "immutable",
    "joi",
    "lodash.sortby",
    "lodash.isobject",
    "lodash.isplainobject",
    "lodash.isarray",
    "lodash.isempty",
    "lodash.debounce",
    "lodash.throttle",
    "lodash.result",
    "lodash.merge",
    "lodash.flatten",
    "react",
    "react/addons",
    "react/lib/ReactLink",
    "react-router",
    "react-document-title"
  ],
```

I don't understand why?

Shouldn't `app.js` contain `react`, `lodash` etc? Is't not duplication?
And current `vendors.js` is 5M!

**Comment by ivan-kleshnin** [comment]
> Shouldn't app.js contain react, lodash etc? Is't not duplication?
No. Separate `vendors.js` is required for faster builds (it's out of watches, caches, etc.)

> And current vendors.js is 5M!
Yes. We can remove **Immutable**, as it's no longer used on frontend. **Immutable** is incompatible with **Baobab** at this moment.
